### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by smiler96** [Ir1d/AFN#1]
Thanks for your great work for Demoireing. After reading your paper and the code. I still have some question. In the paper, is AFN++ a two cascaded AFN1(stage 1) and AFN2(stage 2) network? When the AFN1 trained completely, and then start training the AFN2. Does this mean the parameters of AFN1 in the stage 2 are fixed and are’t updated? Only upade the AFN2’s parameters? 
Also, in your paper, in the stage 2, “augment the input image using flip, transpose and rotate operations” and get the responding generating coarse results from AFN1. But I haven’t seen the related code for the stage 2. Do I miss something else?
Thanks for your reply.

**Comment by Ir1d** [comment]
@smiler96 Hi.
1. AFN++ denotes a two-stage design. After we train AFN1 completely, we fix AFN1 and train AFN2.
2. the code for stage2 is not provided yet in this repo. But it should be simple to implement: 1) run test script for AFN1 and save the result 2) change the dataloader to make it load the generated result 3) train AFN2
