### ISSUE TITLE
AFN difference for track1 and track2 of NTIRE 2020 Deblur

### ISSUE THREAD

**Issue by marghesc** [Ir1d/AFN#4]
AFN paper states the following:

- "trackAFN (Ours) 34.20 0.9392" (Table 5: Quantitative results on NTIRE20 Challenge Deblur)
- "Our AFN has 47.7M parameters, and requires 760G MACs for an input image of size 128 × 128" (4.2. Implementation Details)

AFN competed in track1 and track2 of "NTIRE 2020 Challenge on Image and Video Deblurring" with the results:

- track1: "OIerM Attentive Fractal Network 34.20 0.9392 1.16" (Table 1: Single image deblurring results on the REDS test data)
- track2: "OIerM Attentive Fractal Network 28.33 0.8079 0.9" (Table 2: Single image deblurring results on the REDS test data from Google Pixel 4)

I have 2 questions:

1. what is the diff between AFN network from track1 and AFN network from track2?
2. where can I download the CFAMoire dataset?

Thank you!

**Comment by Ir1d** [comment]
Hi,

1. The AFN network in track2 is much smaller because the environment has strict limitation, iirc (such as flops, layers, etc). The setting in track1 is the same as decribed in the paper.
2. please ask the competition organisers for the dataset.
