### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by Egazaga** [Ir1d/AFN#6]
Hello.
Could you share the pretrained model, please?

**Comment by nhduong** [comment]
> Hello. Could you share the pretrained model, please?

Have you received the pre-trained model from them?

**Comment by Ir1d** [comment]
Hi all, here's the checkpoint originally used to generate the submission in NTIRE'20. https://drive.google.com/file/d/1EMnRnlTmPCZHTekhDh3rgcqRRJiMqPUe/view?usp=sharing
Specific keys might be different because the change in pytorch lightning, but the weights should work
